### ISSUE TITLE
BUG! "check the sensor data before login" 

### ISSUE THREAD

**Issue by alberty4573** [ICTD-Maroubra/PEMS#11]
INFO [pool-1-thread-1] (WebSensor.java:66) - http://eif-research.feit.uts.edu.au/api/json/?rFromDate=2017-10-16T14%3A16%3A22&rToDate=2017-10-16T14%3A26%3A22&rFamily=wasp&rSensor=ES_A_05_181_7BDA&rSubSensor=AP2

I checked this link and the sub sensor does not exist as the others, we should check the content of the sensors api webpage before storing them 
![screen shot 2017-10-16 at 2 32 57 pm](https://user-images.githubusercontent.com/30784533/31594147-012dcdfc-b27f-11e7-803b-ac08c837f69f.png)

**Comment by kutluo** [comment]
This is due to no checking the contents of the webpage. Will change the current implementation to us retrofit to validate the data before storing.

**Comment by kutluo** [comment]
Created unit tests, fixed.
