### ISSUE TITLE
BUG! Check the sensor time!

### ISSUE THREAD

**Issue by alberty4573** [ICTD-Maroubra/PEMS#12]
under the WASP family the sensor unit change through time. 
![screen shot 2017-10-16 at 3 21 01 pm](https://user-images.githubusercontent.com/30784533/31595258-13c98530-b286-11e7-825d-62d6456ebd08.png) this pic shows the available sensors(not every one of them) during the time slot from 14:38-14:48 (the present time is 15:25 same day); with the time changes the more sensors will load the data into the api, pls change the code to cope with the circumstances

**Comment by kutluo** [comment]
Created unit tests, fixed.
