### ISSUE TITLE
GDbus.Error.org.freedesktop.Dbus.Error.UnknownMethod: Method "WriteValue" with signature "aya{sv}" on interface "org.bluez.GattCharacteristic1" doesnt Exist

### ISSUE THREAD

**Issue by Jeremyyiu** [ICTD-Maroubra/PEMS#22]
When running the code, the sensor is discovered, connected to and I can also get the services and characteristics. 

However, when trying to read the value of the characteristics, an error occurs.
`Exception in thread "main" tinyb.BluetoothException: GDbus.Error.org.freedesktop.Dbus.Error.UnknownMethod: Method "WriteValue" with signature "aya{sv}" on interface "org.bluez.GattCharacteristic1" doesn't Exist
           at tinyb.BluetoothGattCharacteristic.writeValue(Native Method)
           at HelloTinyB.main(helloTinyB.java.189)
`
This issue was checked and confirmed to occur in the TinyB java example as well.
The BlueZ version at the time of the issue was: v5.37.

As seen in similar issues, there is no backwards compatibility, therefore to use the latest version of TinyB, BlueZ needs to be updated as well - potentially BlueZ 5.42 or later.

https://github.com/intel-iot-devkit/tinyb/issues/86

To fix this issue follow the following instructions:
---------------------------------------------------------------------------------------------------------
1. Download BlueZ 5.47 - www.bluez.org/release-of-bluez-5-47/
2.  Go to the location where you stored your tar file and run your terminal from there. `tar xfz bluez-5.47.tar.xz` - extract the tar file
3. `cd` to the newly extracted BlueZ folder 
4. `./configure`
5. `make`
6. `sudo make install`
7. `bluetoothd -v` to check the BlueZ version

If it still mentions the previous version before installation, 
'sudo ln -s /usr/local/libexec/bluetooth/bluetoothd /usr/sbin/bluetoothd`
(If it mentions `Failed to create symbolic link '/usr/sbin/bluetoothd`, you can do 'sudo rm /usr/local/libexec/bluetooth/bluetoothd /usr/sbin/bluetoothd` then 'sudo ln -s /usr/local/libexec/bluetooth/bluetoothd /usr/sbin/bluetoothd` and 'sudo make install' again)

Check your Bluez Version 'bluetoothd -v' again - it should now show 5.47.

8. `sudo systemctl restart bluetooth`
9. `sudo systemctl daemon-reload`
10. `sudo hciconfig hci0 up`
11. Run the code again.

Now you should be able to read the values of the characteristics!

**Comment by twgraham** [comment]
Thanks for posting the troubleshooting guide for this @Jeremyyiu
