### ISSUE TITLE
Required parameter "host" not found.

### ISSUE THREAD

**Issue by kutluo** [ICTD-Maroubra/PEMS#3]
If you encounter the following issue when you do a `./gradlew run` this means that the environment variables are not correctly setup.
![host_not_found](https://user-images.githubusercontent.com/31602329/31166909-171c2ca4-a93c-11e7-8787-d17ed5d5405f.png)
You can check your environment variables from terminal with `echo $PEMS_HOST` and `echo $PEMS_PORT`
If you are not getting the following responses that means they are not correctly setup.
![enviroment_vars](https://user-images.githubusercontent.com/31602329/31166948-38263c64-a93c-11e7-9298-cdc85496c5ba.png)

**To set up environment variables:**
1. Open terminal and run `gksudo gedit /etc/environment`
2. Add PEMS_HOST="0.0.0.0" and PEMS_PORT="9005" to the file and save. 
![setting_up_env_vars](https://user-images.githubusercontent.com/31602329/31167190-eae8ee1e-a93c-11e7-800a-feabb633348b.png)
3. Restart your system.
4. Check if your environment variables are setup from terminal with `echo $PEMS_HOST` and `echo $PEMS_PORT`

**Comment by twgraham** [comment]
Technically these should not be required anymore since there are defaults so it should be fixed. Regardless you can also do:

`export PEMS_HOST="0.0.0.0"`
(same for other variables) 

This avoids the need to reboot. 

This will only last for your terminal session though (until you reboot).
