### ISSUE TITLE
Issues with building the project

### ISSUE THREAD

**Issue by lkxlaz** [ICTD-Maroubra/PEMS#9]
Below are the steps to reproduce the error
1. Check out Master branch
2. Right click on PEMS root folder, and go to "Open module settings"
3. In the module settings, mark pems-server/src folder as "Sources" (like the below image).
![wechatimg11735](https://user-images.githubusercontent.com/17043553/31582833-e047c5c0-b1d9-11e7-80fd-a82a31edbb66.jpeg)
4. Completing above steps resulted in failure to build the project (getting 100+ errors as shown in the below pic)
![wechatimg59](https://user-images.githubusercontent.com/17043553/31582844-3aa92f86-b1da-11e7-8c7a-f6dc24d071a8.jpeg)

Can anyone help me out? Thanks

**Comment by twgraham** [comment]
I would try reimport the project from the intellij start screen. When you go to import, go to the `pems-server` folder and import from the `build.gradle` file. That way it should import as a gradle project. Also when it show settings, make sure you check "auto import" for dependencies.

**Comment by lkxlaz** [comment]
I followed @twgraham instructions and the problem solved. By the way, Master branch is having some issues (environment variables) at the moment but the develop branch should be fine.
